### ISSUE TITLE
关于自动获取 IP 地址功能

### ISSUE THREAD

**Issue by LandGrey** [JosephTribbianni/JNDI#1]
`/org/su18/server/ServerStart.java` 文件中的 `getLocalIpByNetCard` 方法：

> 直接根据第一个网卡地址作为其内网ipv4地址

不应该是获取网卡的外网地址嘛，获取内网地址在本地测试用？建议可以让用户在配置文件中指定这个外网地址。

**Comment by JosephTribbianni** [comment]
已更新
